import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
const inter = Poppins({
	subsets: ["latin"],
	weight: ["100", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex">
					<Sidebar />
					<main className="bg-neutral-700 w-full p-[20px] ml-[10%]">
						<Header />
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
